import React from 'react';
import { LegalLayout } from './LegalLayout';

export function TermsPage() {
  return (
    <LegalLayout
      kicker="Legal · Terms"
      title="Terms of Service"
      lastUpdated="June 03, 2026"
    >
      <p>
        These Terms of Service ("Terms") govern your use of ResumeCraft ("the service"). By
        accessing or using the service you agree to be bound by these Terms. If you do not
        agree, do not use the service.
      </p>

      <h2>1. The Service</h2>
      <p>
        ResumeCraft provides AI-assisted resume parsing, optimization, ATS scoring, and PDF
        export. The service relies on third-party AI providers and infrastructure, and may be
        subject to outages, rate limits, or temporary degradation beyond our control. The
        service is offered on an "as is" and "as available" basis.
      </p>

      <h2>2. Eligibility</h2>
      <ul>
        <li>You must be 16 years or older</li>
        <li>You must provide accurate sign-up details</li>
        <li>One account per person; account sharing is prohibited</li>
      </ul>

      <h2>3. Account Responsibilities</h2>
      <ul>
        <li>Keep your password confidential</li>
        <li>Notify us via the Feedback form immediately if you suspect unauthorized account use</li>
        <li>You are responsible for all activity under your account</li>
      </ul>

      <h2>4. Acceptable Use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>Upload resumes containing fabricated credentials with intent to defraud employers</li>
        <li>Submit content that is unlawful, harmful, defamatory, or violates anyone's rights</li>
        <li>Reverse-engineer, scrape, or attempt to bypass rate limits or access controls</li>
        <li>Use the service to train competing AI models</li>
        <li>Resell or sublicense access to others</li>
      </ul>

      <h2>5. Credits and Billing</h2>
      <ul>
        <li>Optimizations consume credits as displayed at checkout</li>
        <li>Credits do not expire while your account is active</li>
        <li>Subscription plans renew at the displayed interval until cancelled</li>
        <li>You may cancel renewal anytime from the Subscription page; access continues until period end</li>
        <li>Currency is determined automatically by your detected region; you may override in Settings</li>
        <li>All sales are final except as covered by the Refund Policy</li>
      </ul>

      <h2>6. AI Output Disclaimer</h2>
      <p>
        Optimization output is generated by machine learning models. We do not guarantee:
      </p>
      <ul>
        <li>That your resume will pass any specific applicant tracking system</li>
        <li>That you will be selected for interviews or jobs</li>
        <li>Factual accuracy of every phrase produced by the model — review every output before use</li>
      </ul>
      <p>
        You remain solely responsible for the accuracy and truthfulness of your resume
        content. Our internal integrity checks remove fabricated numbers and reject altered
        credentials, but you should verify all output before submission to any third party.
      </p>

      <h2>7. Intellectual Property</h2>
      <ul>
        <li>You retain all rights to your resume content</li>
        <li>By uploading content, you grant us a limited, non-exclusive license to process, store, optimize, and display it back to you</li>
        <li>The service software, branding, and prompt design remain our intellectual property</li>
        <li>Optimized output produced for you is yours to use without further license fees</li>
      </ul>

      <h2>8. Service Availability</h2>
      <p>
        We aim for high availability but do not guarantee uninterrupted service. Maintenance,
        provider outages, or rate limits may cause temporary unavailability. We are not liable
        for indirect losses arising from downtime.
      </p>

      <h2>9. Termination</h2>
      <p>
        We may suspend or terminate accounts that violate these Terms, abuse the service, or
        engage in fraudulent payments. You may close your account at any time via the Feedback
        form (category <em>Privacy</em>). Unused credits on a free or refill plan are forfeited
        on closure.
      </p>

      <h2>10. Limitation of Liability</h2>
      <p>
        To the maximum extent permitted by law, our total aggregate liability for any claim
        related to the service is limited to the amount you actually paid us in the 12 months
        preceding the claim. We are not liable for indirect, incidental, consequential,
        special, or punitive damages, including loss of profits, data, or opportunity.
      </p>

      <h2>11. Indemnity</h2>
      <p>
        You agree to indemnify and hold the operator of ResumeCraft harmless from claims,
        damages, or expenses (including legal fees) arising out of your misuse of the service
        or violation of these Terms.
      </p>

      <h2>12. Governing Law and Disputes</h2>
      <p>
        These Terms are governed by the laws of India. Any dispute will first be attempted to
        be resolved through good-faith negotiation. Failing that, disputes will be subject to
        the exclusive jurisdiction of competent courts in India.
      </p>

      <h2>13. Changes to These Terms</h2>
      <p>
        We may update these Terms. Material changes will be announced via in-app notice at
        least 14 days before they take effect. Continued use after the effective date
        constitutes acceptance.
      </p>

      <h2>14. Contact</h2>
      <p>
        Questions about these Terms: use the in-app <strong>Feedback form</strong> and select
        category <em>General</em>.
      </p>
    </LegalLayout>
  );
}
